### ISSUE TITLE
Move Projects and Examples to Separate Repositories

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#40]
# Description

Examples and projects should be in separate repositories.

Prefix repository names with `gen-art-project_` or `gen-art-example_`

Tasks

- [ ] create project repository
- [ ] implement project with [generative-art-library] dependency
- [ ] test project execution locally

**Comment by azurepolarbear** [comment]
Removed project files from repo
